name: CI

on:
  push:
    branches: ['**']
  pull_request:

permissions:
  contents: read

jobs:
  go:
    uses: agoodkind/go-makefile/.github/workflows/_ci.yml@main
    with:
      submodules: recursive
    permissions:
      contents: read
      id-token: write
